# Numpy Basic

In [5]:
import numpy as np

## data type

array의 dtype을 본다. 

In [6]:
arr = np.array([[1., 2, 3], [1, 2, 3]])

In [7]:
arr.dtype

dtype('float64')

.astype()으로 datatype을 변환 가능

In [8]:
arr = arr.astype(np.int32)
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [9]:
arr = np.array([[1., 2, 3], [1, 2, 3]], dtype=np.uint8)
arr.dtype

dtype('uint8')

len(arr.shape) 를 통해서 차원의 갯수를 확인 할 수 있지만,  
아래와 같이 ndim을 통해 차원 수를 return 가능

In [10]:
len(arr.shape)

2

In [11]:
arr.shape

(2, 3)

size 확인

In [12]:
arr.size

6

dtype 확인

In [13]:
arr.dtype

dtype('uint8')

## Reshape

In [14]:
arr.shape

(2, 3)

Reshape 

In [15]:
arr = arr.reshape([1, 6])
arr.shape

(1, 6)

In [16]:
arr = np.array([[1, 2, 3], [1, 2, 3]])

In [17]:
arr.reshape([6]).shape

(6,)

Reshape, -1 활용, -1하면, 다른 차원에 3을 넣으면 3의 나눈 값이 자동으로 들어가게 됩니다.

In [18]:
arr = arr.reshape(-1)
arr.shape

(6,)

In [19]:
arr = arr.reshape(-1, 3)
arr.shape

(2, 3)

random array 생성

In [20]:
arr = np.random.randn(8, 8)
arr.shape

(8, 8)

In [21]:
arr = arr.reshape([32, 2])
arr.shape

(32, 2)

3차원으로 늘리기

In [22]:
arr = arr.reshape(-1, 2, 1, 1, 1, 1)
arr.shape

(32, 2, 1, 1, 1, 1)

In [23]:
arr

array([[[[[[ 0.04918312]]]],



        [[[[-0.64605705]]]]],




       [[[[[-0.36788562]]]],



        [[[[ 0.25774466]]]]],




       [[[[[-0.61131132]]]],



        [[[[-1.44550614]]]]],




       [[[[[ 0.20556773]]]],



        [[[[ 0.2696625 ]]]]],




       [[[[[ 0.22988223]]]],



        [[[[ 0.97709204]]]]],




       [[[[[ 0.30009573]]]],



        [[[[-1.38649877]]]]],




       [[[[[-0.29756756]]]],



        [[[[-0.56622793]]]]],




       [[[[[ 0.24568433]]]],



        [[[[ 0.50728775]]]]],




       [[[[[ 0.75463146]]]],



        [[[[-0.49131403]]]]],




       [[[[[ 0.72561694]]]],



        [[[[-0.95056838]]]]],




       [[[[[ 1.53292249]]]],



        [[[[ 0.73216881]]]]],




       [[[[[ 1.30118732]]]],



        [[[[-0.13378547]]]]],




       [[[[[ 0.21611688]]]],



        [[[[ 0.8528779 ]]]]],




       [[[[[-0.51649881]]]],



        [[[[-0.21448661]]]]],




       [[[[[-0.31353158]]]],



        [[[[ 0.47979836]]]]],




       [[[

## Ravel : 1차원으로 바꾸어 줄 수 있습니다.

In [24]:
arr.shape

(32, 2, 1, 1, 1, 1)

In [25]:
arr = arr.ravel()
arr.shape

(64,)

arr의 차원을 1로 바꿔줌  
## layer를 flatten 할 때 같은 기능이라 생각하면 됩니다.

## arr.reshape(-1) 와 같습니다.

In [27]:
arr.ravel() == arr.reshape(-1)
arr.shape

(64,)

## np.expand_dims()

안의 값은 유지하되 차원 수를 늘리고 싶을 때가 있음  
이럴 때 사용하는 것이 expand_dims  

In [28]:
arr.shape

(64,)

In [29]:
arr = np.expand_dims(arr, -1)
arr.shape

(64, 1)

In [30]:
arr = arr.ravel()

In [31]:
arr.shape

(64,)

In [32]:
arr = np.expand_dims(np.expand_dims(arr, -1), 0)

In [33]:
arr.shape

(1, 64, 1)

## zeros & ones

0으로 채워진 numpy array를 만들 수 있음

In [34]:
zeros = np.zeros([3, 3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
zeros = np.zeros(1)
zeros

array([0.])

In [36]:
ones = np.ones([10, 5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
ones * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [38]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [39]:
arr = np.arange(4, 9)
arr

array([4, 5, 6, 7, 8])

In [40]:
arr = np.arange(10, 20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Index

In [42]:
nums = [1, 2, 3, 4, 5]

In [43]:
nums[2:]

[3, 4, 5]

In [44]:
nums = [1, 2, 3, 4, [1, 2, 3]]
nums

[1, 2, 3, 4, [1, 2, 3]]

In [45]:
nums[4]

[1, 2, 3]

In [46]:
arr[1][2]

5

In [47]:
arr[1, 2]

5

# Slicing

In [48]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [50]:
arr[1:, 1:]

array([[4, 5],
       [7, 8]])

In [51]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Boolean Indexing

In [52]:
data = np.random.randn(3, 3)
data

array([[-0.14875917,  0.38532519,  0.09379213],
       [ 0.95683508,  0.18267434, -0.2413057 ],
       [-1.66772919, -0.6364111 ,  1.47237108]])

In [53]:
data <= 0

array([[ True, False, False],
       [False, False,  True],
       [ True,  True, False]])

In [54]:
data[data <= 0] = 1

In [55]:
data

array([[1.        , 0.38532519, 0.09379213],
       [0.95683508, 0.18267434, 1.        ],
       [1.        , 1.        , 1.47237108]])

# Broadcast

tensorflow나 pytorch로 계산하면 broadcast의 개념도 잘 이해해야 함

broadcast는 연산 하려는 서로 다른 두개의 행렬의 shape가 같지 않고,  
한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일 때  
이를 여러 복사를 하여 연산을 함

In [56]:
import numpy as np

In [57]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [59]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [60]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
arr + np.array([1, 2, 3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

## Math Function

In [62]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [63]:
arr * 5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [64]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [65]:
np.add(arr, 1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
arr + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.multiply(arr, 3)

0~ 2전까지의 숫자로 랜덤하게 사이트는 27개로 사이즈는 3,3,3로 해달라는 뜻입니다. 아래의 경우 0~2 전까지의 숫자를 랜덤하게 사이즈는 9개로, shape는 3 3 이겠죠

In [70]:
arr = np.random.randint(2, size=27).reshape(3, 3, 3)
arr_2 = np.random.randint(2, size=9).reshape(3, 3)

In [71]:
arr.shape, arr_2.shape

((3, 3, 3), (3, 3))

In [72]:
arr + arr_2

array([[[0, 0, 2],
        [1, 1, 2],
        [1, 2, 1]],

       [[1, 0, 1],
        [1, 0, 1],
        [1, 2, 1]],

       [[0, 1, 1],
        [1, 0, 2],
        [0, 2, 1]]])

In [73]:
arr * arr_2

array([[[0, 0, 1],
        [0, 0, 1],
        [0, 1, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 1, 0]],

       [[0, 0, 0],
        [0, 0, 1],
        [0, 1, 0]]])

In [75]:
np.sum(arr)

11

In [76]:
np.sum(arr + arr_2)

26

In [77]:
arr + arr_2

array([[[0, 0, 2],
        [1, 1, 2],
        [1, 2, 1]],

       [[1, 0, 1],
        [1, 0, 1],
        [1, 2, 1]],

       [[0, 1, 1],
        [1, 0, 2],
        [0, 2, 1]]])

In [28]:
np.max(arr + arr_2)

2

In [30]:
np.min(arr + arr_2)

0

In [34]:
np.max(arr + arr_2, -1)

array([[1, 1, 1],
       [1, 2, 1],
       [1, 2, 2]])

In [36]:
arr + arr_2

array([[[0, 1, 1],
        [0, 1, 0],
        [1, 1, 1]],

       [[0, 1, 1],
        [1, 2, 0],
        [1, 0, 1]],

       [[1, 0, 0],
        [0, 2, 1],
        [1, 1, 2]]])

In [38]:
np.sum(arr + arr_2, axis=-1)

array([[2, 1, 3],
       [2, 3, 2],
       [1, 3, 4]])

In [78]:
np.mean(arr)

0.4074074074074074

In [79]:
arr = np.array([1, 6, 3, 7, 3, 2, 9, 0, 2])
arr

array([1, 6, 3, 7, 3, 2, 9, 0, 2])

# arg
6번째의 인덱스가 가장 크다는 뜻입니다.

In [82]:
np.argmax(arr)

6

7번째의 인덱스가 가장 크다는 뜻입니다.

In [81]:
np.argmin(arr)

7

In [ ]:
arr = np.array([3, 5, 6, 6, 3, 3, 1])

# unique 유일한 값만 반환을 합니다.

In [84]:
np.unique(arr)

array([1, 3, 5, 6])